version: 2

sources:
  - name: raw
    database: ZOOM_RAW_SCHEMA
    schema: RAW
    description: Raw data from Zoom platform
    tables:
      - name: users
        description: Raw user data from Zoom
      - name: meetings
        description: Raw meeting data from Zoom
      - name: participants
        description: Raw participant data from Zoom
      - name: feature_usage
        description: Raw feature usage data from Zoom
      - name: webinars
        description: Raw webinar data from Zoom
      - name: support_tickets
        description: Raw support ticket data from Zoom
      - name: licenses
        description: Raw license data from Zoom
      - name: billing_events
        description: Raw billing event data from Zoom

models:
  - name: bz_audit_log
    description: Audit log for tracking bronze layer transformations
    columns:
      - name: record_id
        description: Unique identifier for the audit record
      - name: source_table
        description: Name of the source table being processed
      - name: load_timestamp
        description: Timestamp when the processing occurred
      - name: processed_by
        description: User who processed the data
      - name: processing_time
        description: Time taken to process the data in seconds
      - name: status
        description: Status of the processing (SUCCESS, ERROR, etc.)
  
  - name: bz_users
    description: Bronze layer for users data
    columns:
      - name: user_id
        description: Unique identifier for the user
      - name: user_name
        description: Name of the user
      - name: email
        description: Email address of the user
      - name: company
        description: Company the user belongs to
      - name: plan_type
        description: Type of plan the user has
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from
