version: 2

models:
  - name: bz_audit_log
    description: Audit log for tracking bronze layer transformations
    columns:
      - name: record_id
        description: Unique identifier for the audit record
      - name: source_table
        description: Name of the source table being processed
        data_type: VARCHAR(255)
      - name: load_timestamp
        description: Timestamp when the processing occurred
      - name: processed_by
        description: User who processed the data
      - name: processing_time
        description: Time taken to process the data in seconds
      - name: status
        description: Status of the processing (SUCCESS, ERROR, etc.)
  
  - name: bz_users
    description: Bronze layer for users data
    columns:
      - name: user_id
        description: Unique identifier for the user
      - name: user_name
        description: Name of the user
      - name: email
        description: Email address of the user
      - name: company
        description: Company the user belongs to
      - name: plan_type
        description: Type of plan the user has
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_meetings
    description: Bronze layer for meetings data
    columns:
      - name: meeting_id
        description: Unique identifier for the meeting
      - name: host_id
        description: ID of the user who hosted the meeting
      - name: meeting_topic
        description: Topic of the meeting
      - name: start_time
        description: Start time of the meeting
      - name: end_time
        description: End time of the meeting
      - name: duration_minutes
        description: Duration of the meeting in minutes
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_participants
    description: Bronze layer for participants data
    columns:
      - name: participant_id
        description: Unique identifier for the participant
      - name: meeting_id
        description: ID of the meeting the participant attended
      - name: user_id
        description: ID of the user who participated
      - name: join_time
        description: Time when the participant joined the meeting
      - name: leave_time
        description: Time when the participant left the meeting
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_feature_usage
    description: Bronze layer for feature usage data
    columns:
      - name: usage_id
        description: Unique identifier for the feature usage
      - name: meeting_id
        description: ID of the meeting where the feature was used
      - name: feature_name
        description: Name of the feature used
      - name: usage_count
        description: Count of feature usage
      - name: usage_date
        description: Date when the feature was used
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_webinars
    description: Bronze layer for webinars data
    columns:
      - name: webinar_id
        description: Unique identifier for the webinar
      - name: host_id
        description: ID of the user who hosted the webinar
      - name: webinar_topic
        description: Topic of the webinar
      - name: start_time
        description: Start time of the webinar
      - name: end_time
        description: End time of the webinar
      - name: registrants
        description: Number of registrants for the webinar
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_support_tickets
    description: Bronze layer for support tickets data
    columns:
      - name: ticket_id
        description: Unique identifier for the support ticket
      - name: user_id
        description: ID of the user who created the ticket
      - name: ticket_type
        description: Type of the support ticket
      - name: resolution_status
        description: Status of the ticket resolution
      - name: open_date
        description: Date when the ticket was opened
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_licenses
    description: Bronze layer for licenses data
    columns:
      - name: license_id
        description: Unique identifier for the license
      - name: license_type
        description: Type of the license
      - name: assigned_to_user_id
        description: ID of the user the license is assigned to
      - name: start_date
        description: Start date of the license
      - name: end_date
        description: End date of the license
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_billing_events
    description: Bronze layer for billing events data
    columns:
      - name: event_id
        description: Unique identifier for the billing event
      - name: user_id
        description: ID of the user associated with the billing event
      - name: event_type
        description: Type of the billing event
      - name: amount
        description: Amount associated with the billing event
      - name: event_date
        description: Date of the billing event
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from
