version: 2

sources:
  - name: raw
    description: Raw data from Zoom platform
    tables:
      - name: users
        description: Raw user data from Zoom
      - name: meetings
        description: Raw meeting data from Zoom
      - name: participants
        description: Raw participant data from Zoom
      - name: feature_usage
        description: Raw feature usage data from Zoom
      - name: webinars
        description: Raw webinar data from Zoom
      - name: support_tickets
        description: Raw support ticket data from Zoom
      - name: licenses
        description: Raw license data from Zoom
      - name: billing_events
        description: Raw billing event data from Zoom

models:
  - name: bz_audit_log
    description: Audit log for tracking bronze layer transformations
    columns:
      - name: record_id
        description: Unique identifier for the audit record
        tests:
          - unique
          - not_null
      - name: source_table
        description: Name of the source table being processed
        data_type: VARCHAR(255)
      - name: load_timestamp
        description: Timestamp when the processing occurred
      - name: processed_by
        description: User who processed the data
      - name: processing_time
        description: Time taken to process the data in seconds
      - name: status
        description: Status of the processing (SUCCESS, ERROR, etc.)
  
  - name: bz_users
    description: Bronze layer for users data
    columns:
      - name: user_id
        description: Unique identifier for the user
      - name: user_name
        description: Name of the user
      - name: email
        description: Email address of the user
      - name: company
        description: Company the user belongs to
      - name: plan_type
        description: Type of plan the user has
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_meetings
    description: Bronze layer for meetings data
    columns:
      - name: meeting_id
        description: Unique identifier for the meeting
      - name: host_id
        description: ID of the user who hosted the meeting
      - name: meeting_topic
        description: Topic of the meeting
      - name: start_time
        description: Start time of the meeting
      - name: end_time
        description: End time of the meeting
      - name: duration_minutes
        description: Duration of the meeting in minutes
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from

  - name: bz_participants
    description: Bronze layer for participants data
    columns:
      - name: participant_id
        description: Unique identifier for the participant
      - name: meeting_id
        description: ID of the meeting the participant attended
      - name: user_id
        description: ID of the user who participated
      - name: join_time
        description: Time when the participant joined the meeting
      - name: leave_time
        description: Time when the participant left the meeting
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system the data was extracted from
